app: # fastapi配置
  config: 
    title: 风廓线雷达画图接口
    description: 接口文档描述
    version: 版本号
  cors: # 跨域配置
    allow_origins: ['*']
server: # uvicorn服务器配置
  host: 0.0.0.0
  port: 8001
  reload: true
api: # 外部接口配置
  AQ:
    url: $url
    token:
      access-token: $token
  WPR:
    url: $url
    token:
      key: $key
      value: $value